version: '2'

services: 
  prometheus:
    image: prom/promethus
    container_name: promethus
    volumes: 
      - ./prometheus/:/etc/prometheus/
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
    expose: 
      - 9090
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    container_name: grafana
    expose: 
      - 3000
    ports:
      - 3000:3000
    volumes: 
      - ./grafana/dashboards/:rootfs/opt/grafana/dashboards/
    env_file:
      - ./grafana/gf.config