version: '2'

services: 
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes: 
      - ./prometheus/local/:/etc/prometheus/
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090

  grafana:
    image: appcelerator/grafana
    container_name: grafana
    volumes:
      - ./grafana/configs/:/etc/extra-config/grafana/
    ports:
      - 3000:3000
    environment:
      GRAFANA_PLUGIN_LIST: savantly-heatmap-panel grafana-piechart-panel
      GRAFANA_USER: admin
      GRAFANA_PASS: admin