version: '2'

services: 
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes: 
      - ./prometheus/:/etc/prometheus/
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
    expose: 
      - 9090
    ports:
      - 9090:9090

  grafana:
    # build: grafana/
    image: grafana/grafana
    container_name: grafana
    volumes: 
      - ./grafana/run2.sh:/run2.sh
    expose: 
      - 3000
    ports:
      - 3000:3000
    # env_file:
    #   - ./grafana/gf.config
    command: 
      - /run2.sh