global:
  scrape_interval:     15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']
  # - job_name: 'authorizaton-server'
  #   scrape_interval: 10s
  #   static_configs:
  #     - targets: ['localhost:8080']
  - job_name: 'resource-server'
    scrape_interval: 10s
    metrics_path: '/resource/metrics'
    static_configs:
      - targets: ['192.168.65.1:8080']    
