# FROM grafana/grafana

# VOLUME ["/var/lib/grafana", "/var/log/grafana", "/etc/grafana"]

# EXPOSE 3000

# COPY ./install_datasource.sh /install_datasource.sh

# RUN ["chmod", "+x", "/run2.sh"]
# ENTRYPOINT ["/run2.sh"]